/**
 * GENERATED by scripts/product-photos.mjs. Do not edit by hand.
 *
 * One entry per photo under public/media/shop, one path per width that was
 * actually written. Consumed by `sized()` in shop.ts.
 */

/** The widths that exist on disk, ascending. */
export const OUR_WIDTHS = [200, 400, 700, 1000, 1400] as const;

export const OUR_PHOTOS = {
  'group-premium': {
    200: '/media/shop/group-premium-200.webp',
    400: '/media/shop/group-premium-400.webp',
    700: '/media/shop/group-premium-700.webp',
    1000: '/media/shop/group-premium-1000.webp',
    1400: '/media/shop/group-premium-1400.webp',
  },
  'battery-pump': {
    200: '/media/shop/battery-pump-200.webp',
    400: '/media/shop/battery-pump-400.webp',
    700: '/media/shop/battery-pump-700.webp',
    1000: '/media/shop/battery-pump-1000.webp',
    1400: '/media/shop/battery-pump-1400.webp',
  },
  'court-front': {
    200: '/media/shop/court-front-200.webp',
    400: '/media/shop/court-front-400.webp',
    700: '/media/shop/court-front-700.webp',
    1000: '/media/shop/court-front-1000.webp',
    1400: '/media/shop/court-front-1400.webp',
  },
  'court-side': {
    200: '/media/shop/court-side-200.webp',
    400: '/media/shop/court-side-400.webp',
    700: '/media/shop/court-side-700.webp',
    1000: '/media/shop/court-side-1000.webp',
    1400: '/media/shop/court-side-1400.webp',
  },
  'hand-pump': {
    200: '/media/shop/hand-pump-200.webp',
    400: '/media/shop/hand-pump-400.webp',
    700: '/media/shop/hand-pump-700.webp',
    1000: '/media/shop/hand-pump-1000.webp',
    1400: '/media/shop/hand-pump-1400.webp',
  },
  'pack-side': {
    200: '/media/shop/pack-side-200.webp',
    400: '/media/shop/pack-side-400.webp',
    700: '/media/shop/pack-side-700.webp',
    1000: '/media/shop/pack-side-1000.webp',
    1400: '/media/shop/pack-side-1400.webp',
  },
  'pack-upright': {
    200: '/media/shop/pack-upright-200.webp',
    400: '/media/shop/pack-upright-400.webp',
    700: '/media/shop/pack-upright-700.webp',
    1000: '/media/shop/pack-upright-1000.webp',
    1400: '/media/shop/pack-upright-1400.webp',
  },
  'pack-logo': {
    200: '/media/shop/pack-logo-200.webp',
    400: '/media/shop/pack-logo-400.webp',
    700: '/media/shop/pack-logo-700.webp',
    1000: '/media/shop/pack-logo-1000.webp',
    1400: '/media/shop/pack-logo-1400.webp',
  },
} as const;

export type OurPhoto = keyof typeof OUR_PHOTOS;
